<a href="https://colab.research.google.com/github/LuisIMT/compuIII_2023-1/blob/main/unidad02compuIII.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



Unidad 2

    
---
Matrices

---

```




In [ ]:
M = np.random.randint(0,57,(11,11))
rowvalue = M[:1][0] #todos los valores de la primer fila
colsSigns = [1 if (col % 2 == 0) else -1 for col in range(len(M[0]))] #asignacion de signo
print('matriz original\n',M)
print('valor de fila 0\n',M[0:2-1])
print('resto de la matrix\n',M[1:]) #toda las fila 0
print('la suma \n', M[0:2-1] + M[1:])
#print(M[0:1]) #es equivalente a toda las fila 0
#print(M[1:]) #desde la fila 1, todas las columnas
col = 2
fila = 2
for x in M[0: fila -1] + M[fila-1:]:
    print('valor de fila 0\n',x[0:2-1])
    print('resto de la matrix\n',x[2:]) #toda las fila 0

    print([x[0: col-1] + x[col:]])
print('total\n',[x[0: col-1] + x[col:]])

print('en un linea\n', [x[:col-1] + x[col:] for x in M[0:fila-1] + M[fila:]])

matriz original
 [[42 40  9 19 10 25 53 12 45 40 18]
 [17  9 45 15 13 40 43 26 52 51 43]
 [40 25 34 23 29 45 39 21 41 33  4]
 [ 3 47 44  2 52 25 22 37 21 54 19]
 [44 25 23 31 24 54 46 43 55 53 50]
 [56  1  3 17 16 12 17 48 11 18 24]
 [31 14  7 42 56 47  4 40 23 11 43]
 [55 49 14 38 17 33  7 41 55 22 30]
 [46 53 50 38 10 34 36 17  2 35 46]
 [17 31 40 29 10 34 12 11  0 45 29]
 [47 14 18 45 43 28 52 27  9 52  8]]
valor de fila 0
 [[42 40  9 19 10 25 53 12 45 40 18]]
resto de la matrix
 [[17  9 45 15 13 40 43 26 52 51 43]
 [40 25 34 23 29 45 39 21 41 33  4]
 [ 3 47 44  2 52 25 22 37 21 54 19]
 [44 25 23 31 24 54 46 43 55 53 50]
 [56  1  3 17 16 12 17 48 11 18 24]
 [31 14  7 42 56 47  4 40 23 11 43]
 [55 49 14 38 17 33  7 41 55 22 30]
 [46 53 50 38 10 34 36 17  2 35 46]
 [17 31 40 29 10 34 12 11  0 45 29]
 [47 14 18 45 43 28 52 27  9 52  8]]
la suma 
 [[ 59  49  54  34  23  65  96  38  97  91  61]
 [ 82  65  43  42  39  70  92  33  86  73  22]
 [ 45  87  53  21  62  50  75  49  66  94  37]


In [ ]:

import numpy as np

# compute partial determinant terms
def terms(M, col = 1, row = 1):
    return [x[:col-1] + x[col:] for x in M[0:row-1] + M[row:]]

# compute determinant using first row
def detNxN(M):
    N = len(M[0])
    # Recursion Base: 2x2 determenant
    if (N == 2): 
        M = np.array(M)
        return M[0][0] * M[1,1] - M[0][1] * M[1][0]
    # Recursion Loop
    else: 
        rowValues = M[:1][0] #elemento m11
        colsSigns = [1 if (col % 2 == 0) else -1 for col in range(N)] #loop determina pares + e impares -
        colsDets = [detNxN(terms(M, col + 1)) for col in range(N)] 
        return sum([rowValues[col] * colsSigns[col] * colsDets[col] for col in range(N)])

# compute determinant using optimum row while skipping zero value columns
def smartDetNxN(M):
    N = len(M[0])
    # Recursion Base: 2x2 determenant
    if (N == 2): 
        M = np.array(M)
        return M[0][0] * M[1,1] - M[0][1] * M[1][0]
    # Recursion Loop
    else: 
        # find optimun row
        flatM = [len(np.flatnonzero(x)) for x in M]
        row = flatM.index(min(flatM))
        rowSign = 1 if (row % 2 == 0) else -1
        rowValues = M[row]
        # compute partial determinants
        colsSigns = [1 if (col % 2 == 0) else -1 for col in range(N)]
        colsDets = [smartDetNxN(terms(M, col + 1, row + 1)) if (rowValues[col] != 0) else 0 for col in range(N)]
        return sum([rowValues[col] * rowSign * colsSigns[col] * colsDets[col] for col in range(N)])

# test case for matrix
def testCase(M):
    print()
    N1 = len(M[0])
    N2 = len(M[0])
    A = smartDetNxN(M)
    B = round(np.linalg.det(M))
    print("Matrix %ix%i:" % (N1, N2))
    print("Actual detM = %d, Expected detM = %d " % (A, B))
    print("Test Pass:", A == B)

# main
def main():   
    # Matrix 2 x 2
    M1 = [[1,2,],[0,1]] 
    testCase(M1)
    
    # Matrix 3 x 3
    M2 = [[1,2,3],[2,1,2],[3,2,1]]
    testCase(M2)
    
    # Matrix 4 x 4
    M3 = [[1,2,3,4], [2,1,0,3], [3,0,1,2], [4,0,0,1]]
    testCase(M3)
    
    # Matrix 10 x 10
    M4 = [
        [0,1,2,3,4,5,6,7,8,9],
        [1,1,0,0,0,0,0,0,0,8],
        [2,0,1,0,0,0,0,0,0,7],
        [3,0,0,1,0,0,0,0,0,6],
        [4,0,0,0,1,0,0,0,0,5],
        [5,0,0,0,0,1,0,0,0,4],
        [6,0,0,0,0,0,1,0,0,3],
        [7,0,0,0,0,0,0,1,0,2],
        [8,0,0,0,0,0,0,0,1,1],
        [9,0,0,0,0,0,0,0,0,0],
    ]
    testCase(M4)
main()


Matrix 2x2:
Actual detM = 1, Expected detM = 1 
Test Pass: True

Matrix 3x3:
Actual detM = 8, Expected detM = 8 
Test Pass: True

Matrix 4x4:
Actual detM = 20, Expected detM = 20 
Test Pass: True

Matrix 10x10:
Actual detM = 999, Expected detM = 999 
Test Pass: True


In [ ]:
import numpy as np

class OperacionesMatriciales:
    def __init__(self, M):
        self.M = M

    def matrizmenor(self,columna ,fila ):
        return [x[:columna-1] + x[columna:] for x in self.M[0:fila-1] + self.M[fila:]]

    def detM(self,A):
        if (len(A)==2):
            return A[0,0]*A[1,1] - A[0,1]*A[1,0]
        else:
            flatM = [len(np.flatnonzero(x)) for x in A]
            row = flatM.index(min(flatM))
            rowValues = A[row]
            colsSigns = [1 if (col % 2 == 0) else -1 for col in range(len(A))]
            colsDets = [self.detM(self.matrizmenor(2,2)) if (rowValues[col] != 0) else 0 for col in range(len(A))]
            return sum([rowValues[col] * -1**(col) * colsSigns[col] * colsDets[col] for col in range(len(A))])
            '''for c in range(len(N[0])):
                print(c)
                print(det)
                det += [(-1**(c)*N[i,c]*self.matrizmenor(i,c)*self.detM(N) for i in range(len(N[0])))]'''
        #return det
def main():
    matriz = np.random.randint(-5,5,(5,5))
    print(matriz)
    objOpMat = OperacionesMatriciales(matriz)
    det = objOpMat.detM(matriz)
    print(det)

    B = round(np.linalg.det(matriz))
    print(B)

if __name__ == '__main__':
    main()

[[ 0  1 -1  1  3]
 [ 2  3  2 -3 -1]
 [-4 -4  1 -4  4]
 [-5  0  0 -2  4]
 [ 2  1 -5  2 -1]]


RecursionError: ignored

In [ ]:
import copy
def new_matrix(a,i):#FUNCTION TO FIND THE NEW MATRIX
    arr = copy.deepcopy(a) 
    if len(arr) == 2:
        
        return arr
    else:
        arr.pop(0)
        for j in arr:
            j.pop(i)
            
        return arr
    
def determinant(a):#FUNCTION TO FIND THE DETERMINANT OF A MATRIX
    if len(a) == 1:
        pro = a[0]
        return pro
    elif len(a) == 2:
        pro = a[0][0]*a[1][1] - a[1][0]*a[0][1]
        return pro
            
    else:
        pro = 0
        for i in range(len(a[0])):
            pro += ((-1)**i)*a[0][i]*determinant(new_matrix(a,i))    
        return pro         
            
A = [2]
B = [[1,2,4],[3,4,7],[5,6,7]]
C = [[1,2,3,4],[4,3,5,6],[8,4,2,1],[3,2,4,1]]
D = [[1,3,5,7,9],[4,6,3,7,5],[5,10,8,3,1],[1,5,3,7,6],[8,1,7,5,8]]
print("The determinant of A --> ",determinant(A))
print("The determinant of B --> ",determinant(B))
print("The determinant of C --> ",determinant(C))
print("The determinant of D --> ",determinant(D))

The determinant of A -->  2
The determinant of B -->  6
The determinant of C -->  -99
The determinant of D -->  -687


el bueno

In [59]:
from numpy.core.memmap import dtype

import copy
import random
import time
import numpy as np
class OperacionesMatriciales:
    def __init__(self, M):
        self.M = M
    def nueva_matriz(self,N,i):
        arr = copy.deepcopy(N)
        if (len(arr) == 2):
            return arr
        else:
            #np.delete(arr,0,axis = 0)
            arr.pop(0)
            for j in arr:
                j.pop(i)
                #np.delete(arr,j,axis=1)
            return arr
        
    def determinat(self,N):
        if (len(N) == 1):
            return N[0]
        elif len(N) == 2:
            return N[0][0]*N[1][1] - N[0][1]*N[1][0]
        
        else:
            pro = 0
            for i in range(len(N[0])):
                pro += ((-1)**i*N[0][i]*self.determinat(self.nueva_matriz(N,i)))
            return pro
            
    def trazas(self):
        return [self.M[i][i] for i in range(len(self.M))], sum([self.M[i][i] for i in range(len(self.M))])

    def transpuestaM(self,M):
        N = np.zeros_like(M)
        #print(N)
        for i in range(len(M)):
            for j in range(len(M[0])):
                N[i][j] = M[j][i]
        return N
                

    def propiedadCiclicaTraza(self):
        t = 0
        for i in range(len(self.M[0])):
            for j in range(len(self.M[1])):
                t += self.M[i][j]**2
        return t

    def sumaMatrices(self,A):
        m = int(len(self.M[1]))
        n = int(len(A))
        if (m == n):
            suma = np.zeros((m,n))
            #print(suma)
            for i in range(n):
                for j in range(m):
                    if (j < len(A[0])):
                        suma[i][j] = self.M[i][j] + A[i][j]
                    else:
                        suma[i][j] = self.M[i][j]
            return suma
        else:
            print('no se pueden sumar')

    def restaMatrices(self,A):
        m = int(len(self.M[1]))
        n = int(len(A))
        if (m == n):
            resta = np.zeros((m,n))
            #print(suma)
            for i in range(n):
                for j in range(m):
                    if (j < len(A[0])):
                        resta[i][j] = self.M[i][j] - A[i][j]
                    else:
                        resta[i][j] = -self.M[i][j]
            return resta
        else:
            print('no se pueden restar')
    
    def multiesc(self,num):
        mult = np.zeros_like(self.M)
        for i in range(len(self.M)):
            for j in range(len(self.M[1])):
                mult[i][j] = num*self.M[i][j]
        return mult

    def multimatrices(self,B):
        m = int(len(self.M[1]))
        n = int(len(B))
        if (m == n):
            multiplicacion = np.zeros((len(self.M),len(B[1])))
            for i in range(len(self.M)):
                for j in range(len(B[1])):
                    val = 0
                    for k in range(len(self.M[0])):
                        val += self.M[i][k]*B[k][j] 
                    multiplicacion[i][j] = val
            return multiplicacion

        else:
            print('no se puede multiplicar')


    def bloqueM2x2(self):
        if len(self.M[0]) == 4 and len(self.M[1]) == 4:
            M = np.array(self.M)
            a = np.split(np.hsplit(M,2)[0],2)[0]
            b = np.split(np.hsplit(M,2)[1],2)[0]
            c = np.split(np.hsplit(M,2)[0],2)[1]
            d = np.split(np.hsplit(M,2)[1],2)[1]
            #a = np.split(np.hsplit(M,2)[0],2), np.split(np.hsplit(M,2)[1],2)
            return a,b,c,d
        else:
            return None
    
    def vectorMatrixF(self,M):
        n = len(M)
        vectM = np.zeros((n*n))
        for i in range(n):
            for j in range(n):
                vectM[i*n+j] = M[i][j]     
        return vectM,n

    def vectorMatrixC(self,M):
        n = len(M[0])
        vectM = np.zeros((n*n))
        for i in range(n):
            for j in range(n):
                vectM[j*n+i] = M[i][j]     
        return vectM,n

    def sumavecmat(self,B,M):
        B,n = self.vectorMatrixC(B)
        M,m = self.vectorMatrixC(M)
        c = np.zeros_like(M)
        for i in range(len(c)):
            c[i] = M[i] + B[i]
        return c
        
    def multvecmat(self,A,B):
        A,m = self.vectorMatrixF(A)
        print(A)
        B,n = self.vectorMatrixC(B)
        print(B)
        ma = np.zeros((m*n))
        #i = 0
        if n == m:
            #while (i<=m):
            
            for i  in range(n):
                for k in range(n):
                    for j in range(m):
                        ma[i*n+k] += A[n*i+j]*B[k*n+j] 
                    #print(c)
                    
            return ma
        else:
            print('no se puede')
            return None


    def dispM(self,M):
        dispersa = []
        for i in range(len(M)):
            for j in range(len(M[0])):
                if M[i][j] != 0:
                    dispersa.append([i,j,M[i][j]])
        return dispersa

    def transM(self,N):
        for index,value in enumerate(N):
            '''print(index) indexacion
                print(value[0]) fila i
                print(value[1]) columna j
                print(value[2]) valor w
                print(j)'''
            tmp = value[0]
            value[0] = value[1]
            value[1] = tmp
            
        return N
    def trazaMdisp(self,N):
        traza = 0
        for index,value in enumerate(N):
            #for j in range(1):
            if value[0] == value[1]:
                #if index == value[j] and index == value[j]:
                #print(index, value[0],index, value[1])
                traza += value[2]
        return traza

    def norm(self,V):
        normv = 0
       
        value, n = V
        #print(n)
        #print(value)
        #print(n[0]**2+n[1]**2)
        for i in range(len(value)):
            normv += value[i]**2
        return np.sqrt(normv)

    def normP(self,V,p):
        normv = 0
       
        value, n = V
        #print(n)
        #print(value)
        #print(n[0]**2+n[1]**2)
        for i in range(len(value)):
            normv += value[i]**p
        return (normv)**(1/p)

    def norml1(self,M):
        fila = np.zeros((len(M)))
        for i,j in enumerate(M):
            fila[i] = sum(j)
        return max(fila)

    def normlinf(self,M):
        n = len(M[0])
        col = np.zeros(n)
        M = self.transpuestaM(M)
        for i,j in enumerate(M):
            col[i] = sum(j)
            print(i)
            #print(j*n)
            print(col)
        return max(col)

def main():
    #matriz = [[1,2,4],[3,4,7],[5,6,7]]
    matriz = np.random.randint(-5,20,(4,4))
    M = matriz.tolist()
    print(matriz)
    objOpM = OperacionesMatriciales(M)
    '''print(objOpM.determinat(M))
    #print(round(np.linalg.det(matriz)))
    print(objOpM.trazas())
    print(objOpM.propiedadCiclicaTraza())
    matriz2 = np.random.randint(-10,10,(8,5))
    print(objOpM.sumaMatrices(matriz2))
    print(objOpM.restaMatrices(matriz2))
    print(objOpM.multiesc(2))
    print(objOpM.multimatrices(matriz2))'''
    #A,B,C,D = objOpM.bloqueM2x2()
    #print(objOpM.vectorMatrixF())
    #matriz2 = np.random.randint(-10,10,(4,4))
    matriz_transpuesta = objOpM.transpuestaM(matriz)
    '''print(matriz)
    print(objOpM.vectorMatrixF(matriz))
    #print(objOpM.vectorMatrixC(matriz2))
    #print(objOpM.sumavecmat(matriz,matriz2))
    #print('multiplicacion normal\n',objOpM.multimatrices(matriz2))
    #print('multiplicacion vectorial:',objOpM.multvecmat(matriz,matriz2))
    #matrices_dispersa =  objOpM.dispM()
    #print('matriz dispersa', matrices_dispersa)
    #print(matrices_dispersa[(1,2)])'''
    #print('matriz dispersa transpuesta', objOpM.tranDispM(matrices_dispersa))
    m_d1 =  objOpM.dispM(matriz)
    #print(matrices_dispersa)
    #print(objOpM.transM(m_d1))
    #print(objOpM.trazaMdisp(m_d1))
    #vector = objOpM.vectorMatrixF(matriz) #return el array y el tamaño de la fila
    #print(objOpM.norm(vector)) 
    #print(objOpM.normP(vector,3))
    #objOpM = OperacionesMatriciales(m_d1)
    print(objOpM.norml1(m_d1))
    print(objOpM.norml1(matriz_transpuesta))

if __name__ == '__main__':
    main()            


[[16 19 -1  0]
 [-4 19  7 14]
 [10 -1  3  3]
 [-1  5  2 12]]
21.0
42.0


In [5]:

class Sparse:
    def __init__(self, row, col, value):
        self.row = row
        self.col = col
        self.value = value

class InitMatrix:

    def initRandomMat(self, M):
        numElements = int ((len(M)*len(M[0])) * 0.1) # 10% de elementos distintos de 0
        count = 0
        for i in range(len(M)):
            for j in range(len(M[0])):
                if(random.random() >= 0.9):
                    if(count >= numElements):
                        break
                    M[i][j] = random.randint(1, 10)
                    count+=1
        return M

class SparseOps:

    def transposeMat(self, M):
        start = time.time()
        for i in range(len(M)):
            tmp = M[i].row
            M[i].row = M[i].col 
            M[i].col = tmp
        end = time.time()
        print("Matrix" + str(M))
        print("Total time sparse mat: ", end-start)
        return M, end-start

    def printMat(self, M):
            for i in range(len(M)):
                print("Mat: ", M[i].row , M[i].col , " =>", M[i].value )
    # Suma, resta, multiplicación.

    def suma(self,M,N):
        start = time.time()
        n = len(M)+len(N)
        print(type(M))
        print(len(M))
        print(len(N))
        print(n)
        mn = []
        for i in range(min(len(M),len(N))):
            if M[i].row != N[i].row:# and M[i].col != N[i].col:
                mn.append(M[i].row + N[i].row)
                #mn.append(N[i].row)
            else:
                mn.append(M[i].row)
                mn.append(N[i].row)
        end = time.time()
        print(mn)
        for i in range(len(mn)):
            print("Mat: ", mn[i].row , mn[i].col , " =>", mn[i].value )
        return mn , end-start



class ConventionalOps:
    def tranposeMat(self, M):
        start = time.time()
        M2 = np.zeros_like(M)
        for i in range(len(M)):
            for j in range(len(M[0])):
                M2[j][i] = M[i][j]
        end = time.time()
        print("Total time conventional: ", end-start)
        return M2, end-start

def main():
    
    # Importar matrix dispersa M1, M2 se asume que existen estas matrices
    n = 10
    f = n
    c = n

    M = np.zeros((f, c), dtype = np.float)
    N = np.zeros((f, c), dtype = np.float)
    objInit = InitMatrix()

    M = objInit.initRandomMat(M)
    N = objInit.initRandomMat(N)
    #print("Matriz aleatoria: \n", str(M))

    sparseMatM = list()
    sparseMatN = list()
    for i in range(len(M)):
        for j in range (len(M[0])):
            if  (M[i][j] != 0):
                sparseMatM.append(Sparse(i, j, M[i][j]))
            if  (N[i][j] != 0):
                sparseMatN.append(Sparse(i, j, N[i][j]))


    #TODO: Calcular una matriz transpuesta
    objOps = SparseOps()
    objConv = ConventionalOps()

    Mtmp, t1 = objConv.tranposeMat(M)
    
    print("Mariz M")
    objOps.printMat(sparseMatM)
    print("Mariz N")
    objOps.printMat(sparseMatN)
    sumMS = sparseMatN+sparseMatM
    print('suma')
    suma = objOps.suma(sparseMatM,sparseMatN)
    #objOps.printMat(suma)
    '''print("Mariz transpuesta")
    M , t2 = objOps.transposeMat(sparseMat)
    #objOps.printMat(M)

    objOps.printMat(M)
    acc = t1 / t2
    print("Aceleración: ", acc)
    #Calcular operaciónes sencillas: sumas, restas, etc ... 


    N = np.zeros((f, c), dtype = np.float)
    #objInit = InitMatrix()

    N = objInit.initRandomMat(N)


    print(N)'''
    

if __name__ == "__main__":
    main() 

Total time conventional:  0.00025391578674316406
Mariz M
Mat:  4 6  => 7.0
Mat:  6 8  => 6.0
Mat:  7 6  => 3.0
Mat:  8 1  => 8.0
Mat:  8 3  => 10.0
Mat:  9 9  => 10.0
Mariz N
Mat:  0 5  => 6.0
Mat:  0 8  => 2.0
Mat:  1 0  => 3.0
Mat:  1 3  => 8.0
Mat:  2 5  => 6.0
Mat:  2 7  => 5.0
Mat:  3 2  => 10.0
Mat:  3 9  => 7.0
Mat:  4 4  => 3.0
Mat:  4 6  => 2.0
suma
<class 'list'>
6
10
16
[4, 6, 8, 9, 10, 11]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:80: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:81: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


AttributeError: ignored